/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const LoginLazyImport = createFileRoute('/login')()
const LandingRegisterLazyImport = createFileRoute('/LandingRegister')()

// Create/Update Routes

const LoginLazyRoute = LoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const LandingRegisterLazyRoute = LandingRegisterLazyImport.update({
  id: '/LandingRegister',
  path: '/LandingRegister',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/LandingRegister.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/LandingRegister': {
      id: '/LandingRegister'
      path: '/LandingRegister'
      fullPath: '/LandingRegister'
      preLoaderRoute: typeof LandingRegisterLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/LandingRegister': typeof LandingRegisterLazyRoute
  '/login': typeof LoginLazyRoute
}

export interface FileRoutesByTo {
  '/LandingRegister': typeof LandingRegisterLazyRoute
  '/login': typeof LoginLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/LandingRegister': typeof LandingRegisterLazyRoute
  '/login': typeof LoginLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/LandingRegister' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/LandingRegister' | '/login'
  id: '__root__' | '/LandingRegister' | '/login'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LandingRegisterLazyRoute: typeof LandingRegisterLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  LandingRegisterLazyRoute: LandingRegisterLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/LandingRegister",
        "/login"
      ]
    },
    "/LandingRegister": {
      "filePath": "LandingRegister.lazy.jsx"
    },
    "/login": {
      "filePath": "login.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
